# Generated by Django 3.0.3 on 2021-03-03 19:40

import core.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='answers/')),
                ('liked', models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=core.models.generate_unique_code, max_length=8, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='classes/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('day', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
                ('deadline', models.DateTimeField(default=datetime.datetime.today)),
                ('answers', models.ManyToManyField(blank=True, related_name='answered', to='core.Answer')),
                ('lesson', models.ForeignKey(default='reza', on_delete=django.db.models.deletion.CASCADE, to='core.Lesson')),
                ('ostad', models.ForeignKey(default='reza', on_delete=django.db.models.deletion.CASCADE, to='core.Master')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_answer', models.ManyToManyField(blank=True, related_name='user_answer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ClassRoom'),
        ),
        migrations.AddField(
            model_name='answer',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
