# Generated by Django 3.0.3 on 2021-02-21 15:41

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=core.models.generate_unique_code, max_length=8, unique=True)),
                ('ostad', models.CharField(max_length=100)),
                ('lesson_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('day', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
                ('deadline', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
