# Generated by Django 3.0.3 on 2021-02-23 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210223_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image_answer', models.ImageField(upload_to='answers/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ClassRoom')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='answered', to='core.Answer'),
        ),
    ]
