# Generated by Django 3.0.3 on 2021-02-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210223_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='classes/'),
        ),
    ]
