# Generated by Django 3.0.3 on 2021-02-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_answer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='user',
        ),
    ]
