# Generated by Django 3.0.3 on 2021-02-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210226_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='username',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='user',
        ),
        migrations.AlterField(
            model_name='answer',
            name='image_answer',
            field=models.ImageField(blank=True, null=True, upload_to='answers/'),
        ),
    ]
