# Generated by Django 3.0.3 on 2021-03-01 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210228_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='user_answer',
            field=models.ManyToManyField(blank=True, related_name='user_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
