# Generated by Django 3.0.3 on 2021-03-02 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210302_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
